### ISSUE TITLE
Broken lines

### ISSUE THREAD

**Issue by omani** [gosuri/uilive#18]
Hi,
I thought I've finally found a lib which makes it easy to use single-line prints, but this lib suffers from the same issue I've seen in many other libs.

demo:
```
writer := uilive.New()
// start listening for updates and render
writer.Start()

for i := 0; i <= 100; i++ {
  fmt.Fprintf(writer, "Downloading.. (%d/%d) GB\n", i, 100)
  time.Sleep(time.Millisecond * 5)
}

fmt.Fprintln(writer, "Finished")
writer.Stop() // flush and stop rendering
```

try `fmt.Fprintln(writer, "Finished")` instead of `fmt.Fprintln(writer, "Finished: Downloaded 100GB")`.
meaning: print a last message which is shorter than the previous one.

I get:
```
Finisheding.. (100/100) GB
```

**Comment by asahasrabuddhe** [comment]
Hello @omani ,

This might be a little late for you but I have since managed to fix this issue.

![render1554921937831-min](https://user-images.githubusercontent.com/25657923/55905340-661d0500-5bef-11e9-90e5-9b5f5fe63228.gif)

I am maintaining a fork of this wonderful library https://github.com/asahasrabuddhe/uilive during the time @gosuri is busy elsewhere. Join me there in making this library even better!

**Comment by omani** [comment]
thank you very much @asahasrabuddhe. after such a long time you thought about me :)

**Comment by asahasrabuddhe** [comment]
Better late than never right @omani?
